name: Build MT6789 Kernel

on:
  workflow_dispatch:
    inputs:
      CLEAN_BUILD:
        description: 'Clean before building?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      EXTRACT_MODULES:
        description: 'Extract and zip modules?'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean space (if selected)
        if: github.event.inputs.CLEAN_BUILD == 'true'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync m4 schedtool squashfs-tools xsltproc zip zlib1g-dev python3 python-is-python3 python2.7 openssl lz4 patch
          sudo ln -sf /usr/bin/python2.7 /usr/bin/python2

      - name: Download and Extract Toolchain
        run: |
          sudo apt-get install python2 pahole libelf-dev -y
          DIR="$(readlink -f .)"
          PARENT_DIR="$(readlink -f "${DIR}/..")"
          git clone https://gitlab.com/tejas101k/clang-r450784d.git/ "$PARENT_DIR/clang-r450784d" --depth=1
      - uses: rui314/setup-mold@v1

      - name: Set Scripts Executable
        run: |
          chmod +x build_kernel.sh
          chmod +x scripts/config
          chmod +x scripts/repack
          chmod +x scripts/bin/magiskboot
          chmod +x scripts/bin/ksud-x86_64-unknown-linux-musl
          chmod +x scripts/bin/avb/avbtool.py

      - name: Build and Package
        id: build_chain
        run: |
          ./build_kernel.sh
          
          if [ "${{ github.event.inputs.EXTRACT_MODULES }}" == "true" ]; then
            mkdir -p modules_extracted
            find out/ -name "*.ko" -exec cp {} modules_extracted/ \;
            zip -r kernel_modules.zip modules_extracted/
            rm -rf modules_extracted
          fi
          
          ./scripts/repack
          FINAL_TAR=$(ls -t *.tar | head -n 1)
          if [ -z "$FINAL_TAR" ]; then
            echo "::error::Final .tar file not found!"
            exit 1
          fi
          echo "final_tar_name=$FINAL_TAR" >> $GITHUB_OUTPUT

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Kernel
          path: |
            ${{ steps.build_chain.outputs.final_tar_name }}
            kernel_modules.zip
          if-no-files-found: warn

